runs:
  using: "composite"

  steps:

  - name: configure
    shell: bash
    run: >-
      cmake
      --preset default
      -DMUMPS_parallel:BOOL=${{ matrix.parallel }}
      -DMUMPS_scotch:BOOL=${{ matrix.scotch }}
      -DMUMPS_metis:BOOL=${{ matrix.metis }}
      -DMUMPS_parmetis:BOOL=${{ matrix.parmetis }}
      -DLAPACK_VENDOR=${{ matrix.lapack_vendor }}
      -DMUMPS_openmp:BOOL=${{ matrix.openmp }}

  - name: build, test release
    shell: bash
    run: cmake --workflow default

  - name: install package
    shell: bash
    run: cmake --install build
