runs:
  using: "composite"

  steps:

  - name: Install prereqs (Linux)
    shell: bash
    if: runner.os == 'Linux'
    run: |
      sudo apt update
      sudo apt install --no-install-recommends liblapack-dev

  - name: install open-mpi (linux)
    shell: bash
    if: ${{ runner.os == 'Linux' && !matrix.mpich }}
    run: sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin libscalapack-openmpi-dev

  - name: install MPICH (linux)
    shell: bash
    if: ${{ runner.os == 'Linux' && matrix.mpich }}
    run: sudo apt install --no-install-recommends libmpich-dev mpich
# libscalapack-mpich-dev is broken, it pulls in openmpi-bin, which leads to OpenMPI clashing with MPICH
# https://packages.ubuntu.com/noble/libscalapack-mpich2.2

  - name: install Scotch prereqs (Linux)
    shell: bash
    if: ${{ runner.os == 'Linux' && matrix.scotch}}
    run: |
      sudo apt install --no-install-recommends bison flex

  - name: Install prereqs (macOS)
    shell: bash
    if: runner.os == 'macOS'
    run: brew install open-mpi scalapack

  - name: install Scotch prereqs (macOS)
    shell: bash
    if: ${{ runner.os == 'macOS' && matrix.scotch }}
    run: |
      brew install bison flex

  - name: Install OpenBLAS (Linux)
    shell: bash
    if: ${{ runner.os == 'Linux' && matrix.lapack_vendor == 'OpenBLAS' }}
    run: sudo apt install --no-install-recommends libopenblas-dev
