runs:
  using: "composite"

  steps:

  - name: configure example
    shell: bash
    run: cmake -S example -B example/build

  - name: build example
    shell: bash
    run: cmake --build example/build

  - name: test example
    shell: bash
    run: ctest --test-dir example/build -V

  - name: Scotch example
    shell: bash
    if: ${{ matrix.scotch }}
    run: |
      cmake -S example/scotch -Bexample/scotch/build
      cmake --build example/scotch/build
      ctest --test-dir example/scotch/build -V

  - name: Upload log failure
    if: ${{ failure() && matrix.scotch }}
    uses: actions/upload-artifact@v4
    with:
      name: Scotch-example-${{ runner.os }}-CMakeConfigureLog.yaml
      path: example/scotch/build/CMakeFiles/CMakeConfigureLog.yaml

  - name: METIS example
    shell: bash
    if: ${{ matrix.metis }}
    run: |
      cmake -S example/metis -Bexample/metis/build
      cmake --build example/metis/build
      ctest --test-dir example/metis/build -V

  - name: Upload log failure
    if: ${{ failure() && matrix.metis }}
    uses: actions/upload-artifact@v4
    with:
      name: METIS-example-${{ runner.os }}-CMakeConfigureLog.yaml
      path: example/metis/build/CMakeFiles/CMakeConfigureLog.yaml


  - name: OpenMP example
    shell: bash
    if: ${{ matrix.openmp }}
    run: |
      cmake -S example/openmp -Bexample/openmp/build
      cmake --build example/openmp/build
      ctest --test-dir example/openmp/build -V

  - name: Upload log failure
    if: ${{ failure() && matrix.openmp }}
    uses: actions/upload-artifact@v4
    with:
      name: OpenMP-example-${{ runner.os }}-CMakeConfigureLog.yaml
      path: example/openmp/build/CMakeFiles/CMakeConfigureLog.yaml
