# Disabled because of TLS problems and failure to find lapack,
# while it works on a real Windows lapop.

name: ci_windows

env:
  CMAKE_GENERATOR: Ninja
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"
      - "!scripts/*"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      id: msys2
      with:
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc-fortran
          mingw-w64-ucrt-x86_64-lapack

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ steps.msys2.outputs.msys2-location }}/ucrt64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - name: config
      run: cmake --preset default -DMUMPS_parallel:BOOL=false --install-prefix=${{ runner.temp }}
      env: &lapack
        LAPACK_ROOT: ${{ steps.msys2.outputs.msys2-location }}/ucrt64

    - name: build, test
      run: cmake --workflow --preset default

    - name: install package
      run: cmake --install build

    - name: configure example
      run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH=${{ runner.temp }}
      env: *lapack

    - name: Upload log failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: example-${{ runner.os }}-CMakeConfigureLog.yaml
        path: example/build/CMakeFiles/CMakeConfigureLog.yaml

    - name: build example
      run: cmake --build example/build

    - name: test example
      run: ctest --test-dir example/build -V
