name: oneapi-linux

env:
  CC: icx
  CXX: icpx
  FC: ifx
# https://github.com/oneapi-src/oneapi-ci/blob/master/.github/workflows/build_all.yml
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_TYPE: Release
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs
  CMAKE_GENERATOR: Ninja
# don't need Ninja but it prints the command lines by default which is good for debugging

  # debug triggers asan build errors, peculiar to GitHub Actions

on:
  push:
    paths:
      - "**.c"
      - "**.f"
      - "**.F"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/oneapi-linux.yml"
      - ".github/workflows/oneapi*.sh"
      - "!memcheck.cmake"
      - "!coverage.cmake"
      - "!example/*"
      - "!scripts/*"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    name: parallel=${{ matrix.parallel }} int64=${{ matrix.int64 }}

    strategy:
      matrix:
        int64: [true, false]
        parallel: [true, false]
        oneapi: [2025.2]

    steps:
    - uses: actions/checkout@v4

    - name: cache install oneAPI
      id: cache-install
      uses: actions/cache@v4
      with:
        path: |
          /opt/intel/oneapi
        key: oneapi-${{ matrix.oneapi }}-apt

    - name: non-cache install oneAPI
      if: steps.cache-install.outputs.cache-hit != 'true'
      timeout-minutes: 10
      run: |
        .github/workflows/oneapi_setup_apt_repo_linux.sh
        sudo apt install --no-install-recommends \
          intel-oneapi-compiler-dpcpp-cpp-${{ matrix.oneapi }} \
          intel-oneapi-compiler-fortran-${{ matrix.oneapi }} \
          intel-oneapi-mkl-${{ matrix.oneapi }} \
          intel-oneapi-mkl-devel-${{ matrix.oneapi }} \
          intel-oneapi-mpi \
          intel-oneapi-mpi-devel

    - name: Setup Intel oneAPI environment
      run: |
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV

    - name: Tell MPI compiler wrapper flags
      run: mpiifx -show

    - name: CMake Configure
      run: >-
        cmake --preset default
        -DMUMPS_intsize64=${{ matrix.int64 }}
        -DMUMPS_parallel:BOOL=${{ matrix.parallel }}

    - name: Upload log failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: oneapi-${{ matrix.oneapi }}-${{ runner.os }}-CMakeConfigureLog.yaml
        path: build/CMakeFiles/CMakeConfigureLog.yaml

    - name: CMake build
      run: cmake --build --preset default

    - name: CMake Test
      if: ${{ matrix.int64 == 'false' }}
      run: ctest --preset default

    - name: install package
      run: cmake --install build

    - name: configure example
      run: >-
        cmake
        -S example
        -B example/build

    - name: build example
      run: cmake --build example/build

    - name: test example
      if: ${{ matrix.int64 == 'false' }}
      run: ctest --test-dir example/build -V


    - name: exclude unused files from cache
      if: steps.cache-install.outputs.cache-hit != 'true'
      run: .github/workflows/oneapi_cache_exclude_linux.sh
